In [44]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [17]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.Collecting scikit-learn
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 262.6 kB/s eta 0:00:41
   ---------------------------------------- 0.0/10.6 MB 245.8 kB/s eta 0:00:43
   ---------------------------------------- 0.1/10.6 MB 273.8 kB/s eta 0:00:39
   ---------------------------------------- 0.1/10.6 MB 286.7 kB/s eta 0:00:37
   ---------------------------------------- 0.1/10.6 MB 291.5 kB/s eta 0:00:37
   ---------------------------------------- 0.1/10.6 MB 297.7 kB/s eta 0:00:36
   ---------------------------------------- 0.1/10.6 MB 288.8 kB/s eta 0:00:37
    --------------------------------------- 0.1/10.6 MB 315.4 kB/s eta 0:00:34
    --------------------------------------- 0.2/10.6 MB 327.5 kB/s et

In [45]:
tf.__version__

'2.10.0'

In [46]:
dataset = pd.read_csv(r'F:\Full stack data science\Notes\15th May 2024 Deep learning ANN\10th, 14th, 15th - ANN,GPU,Deep Learning\Practicle - CPU\ANN_ 1st\Churn_Modelling.csv')

In [47]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [68]:
X = dataset.iloc[:,3:-1].values
y= dataset.iloc[:,-1].values

In [69]:
X[2]

array([502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
      dtype=object)

In [70]:
y.shape

(10000,)

In [71]:
X[:,2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

# encoding categorical data
### label encode the gender data

In [72]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [73]:
X[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [75]:
type(X)

numpy.ndarray

# one hot encoder for geogrpahy column

In [76]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [77]:
geography = X[:,1]
geography

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [80]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder(sparse_output=False)
geography = np.reshape(geography,(-1,1))
geography = oh.fit_transform(geography)


In [84]:
print(geography)
print(oh.get_feature_names_out(['Geography']))

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
['Geography_France' 'Geography_Germany' 'Geography_Spain']


In [43]:
print(oh.get_feature_names_out(['CreditScore','Geography','Gender',	'Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary']))

['CreditScore_350' 'CreditScore_351' 'CreditScore_358' ...
 'EstimatedSalary_199953.33' 'EstimatedSalary_199970.74'
 'EstimatedSalary_199992.48']


In [86]:
X[:,1]

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [87]:
X = np.delete(X,1,axis = 1)

In [88]:
X

array([[619, 0, 42, ..., 1, 1, 101348.88],
       [608, 0, 41, ..., 0, 1, 112542.58],
       [502, 0, 42, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 36, ..., 0, 1, 42085.58],
       [772, 1, 42, ..., 1, 0, 92888.52],
       [792, 0, 28, ..., 1, 0, 38190.78]], dtype=object)

In [90]:
X = np.hstack((X,geography))

In [91]:
X

array([[619, 0, 42, ..., 1.0, 0.0, 0.0],
       [608, 0, 41, ..., 0.0, 0.0, 1.0],
       [502, 0, 42, ..., 1.0, 0.0, 0.0],
       ...,
       [709, 0, 36, ..., 1.0, 0.0, 0.0],
       [772, 1, 42, ..., 0.0, 1.0, 0.0],
       [792, 0, 28, ..., 1.0, 0.0, 0.0]], dtype=object)

In [92]:
X.shape

(10000, 12)

# feature scaling

In [93]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
X =sc.fit_transform(X)

In [94]:
X

array([[-0.32622142, -1.09598752,  0.29351742, ...,  0.99720391,
        -0.57873591, -0.57380915],
       [-0.44003595, -1.09598752,  0.19816383, ..., -1.00280393,
        -0.57873591,  1.74273971],
       [-1.53679418, -1.09598752,  0.29351742, ...,  0.99720391,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -1.09598752, -0.27860412, ...,  0.99720391,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.91241915,  0.29351742, ..., -1.00280393,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.09598752, -1.04143285, ...,  0.99720391,
        -0.57873591, -0.57380915]])

# split the data set into train and test

In [100]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.2)

In [101]:
X_train

array([[ 0.17042381, -1.09598752, -0.4693113 , ..., -1.00280393,
        -0.57873591,  1.74273971],
       [-2.31280236,  0.91241915,  0.29351742, ..., -1.00280393,
         1.72790383, -0.57380915],
       [-1.19535058, -1.09598752, -0.94607926, ...,  0.99720391,
        -0.57873591, -0.57380915],
       ...,
       [ 0.90504489,  0.91241915, -0.37395771, ...,  0.99720391,
        -0.57873591, -0.57380915],
       [-0.62627792, -1.09598752, -0.08789694, ..., -1.00280393,
        -0.57873591,  1.74273971],
       [-0.28483432, -1.09598752,  0.86563897, ..., -1.00280393,
         1.72790383, -0.57380915]])

# build the Ann model

In [104]:
ann =tf.keras.models.Sequential()

# adding the first input layer and hidden layer

In [105]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### add second hidden layer

In [108]:
ann.add(tf.keras.layers.Dense(units =6 , activation ='relu'))

### adding the output layer

In [109]:
ann.add(tf.keras.layers.Dense(units =1,activation ='sigmoid'))

# training the ann
### compiling the ann

In [111]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

## training the ANN

In [112]:
ann.fit(X_train,y_train,batch_size =32,epochs=3)

Epoch 1/3
250/250 [==============================] - 5s 4ms/step - loss: 0.6328 - accuracy: 0.6528
Epoch 2/3
250/250 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.8006
Epoch 3/3
250/250 [==============================] - 1s 3ms/step - loss: 0.4288 - accuracy: 0.8136


In [115]:
y_pred =ann.predict(X_test)

63/63 [==============================] - 1s 11ms/step


In [118]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0.26777726 0.        ]
 [0.24363343 1.        ]
 [0.11779019 0.        ]
 ...
 [0.25371462 0.        ]
 [0.14607528 0.        ]
 [0.21222059 0.        ]]


In [119]:
ann.fit(X_train,y_train,batch_size =32,epochs=5)

Epoch 1/5
250/250 [==============================] - 1s 3ms/step - loss: 0.4109 - accuracy: 0.8206
Epoch 2/5
250/250 [==============================] - 1s 3ms/step - loss: 0.3977 - accuracy: 0.8263
Epoch 3/5
250/250 [==============================] - 1s 3ms/step - loss: 0.3868 - accuracy: 0.8339
Epoch 4/5
250/250 [==============================] - 1s 3ms/step - loss: 0.3777 - accuracy: 0.8390
Epoch 5/5
250/250 [==============================] - 1s 3ms/step - loss: 0.3701 - accuracy: 0.8460


In [125]:
y_pred =ann.predict(X_test)

y_pred = (y_pred>0.5)
print(y_pred)
print(y_pred.shape , y_test.shape)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]
(2000, 1) (2000,)
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [126]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1520   75]
 [ 223  182]]
